<?php include("inc/navigation.php"); ?>
<?php include("inc/sidebar.php"); ?>
<title>Admin panel || Home</title>
<style>
#home{
  background-color:green;
}
</style>

<article class="maincontent clear">
    <div class="content">

some text will be go there...some text will be go there...
some text will be go there...some text will be go there...
some text will be go there...some text will be go there...
some text will be go there...some text will be go there...
some text will be go there...some text will be go there...
some text will be go there...some text will be go there...
some text will be go there...some text will be go there...
some text will be go there...some text will be go there...
some text will be go there...some text will be go there...
some text will be go there...some text will be go there...

  </div>
</article>


<?php include("inc/copyright.php"); ?>